name: CI

on:
  # Run on pushes to main
  push:
    branches:
      - main
  # Run on pull requests
  pull_request:
  # Run when manually invoked
  workflow_dispatch:

jobs:
  # Job which lints and formats via ruff
  lint-and-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install ruff
        run: |
          python3 -m pip install ruff

      - name: ruff check
        idf: ruff-check
        continue-on-error: true
        run: |
          python3 -m ruff check --output-format=github

      - name: ruff format --check
        id: ruff-format
        continue-on-error: true
        run: |
          python3 -m ruff format --check

      # if ruff check or ruff format failed, the whole job should fail (but both should be checked)
      - name: Output job status
        if: steps.ruff-check.outcome == "failure" || steps.ruff-format.outcome == "failure"
        run: | 
          echo "ruff check or ruff format --check failed"
          exit 1
        